# -*- coding: utf-8 -*-
"""week8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16mg3L-pa2ts83efF3tZ9OaVkFVP1X93p
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, SimpleRNN # Added SimpleRNN import
from sklearn.metrics import confusion_matrix, classification_report
vocab_size=10000
max_len=200
(x_train,y_train),(x_test,y_test)=imdb.load_data(num_words=vocab_size)
x_train=pad_sequences(x_train,maxlen=max_len)
x_test=pad_sequences(x_test,maxlen=max_len)
print("Training Samples:",x_train.shape)
print("Testing Samples:",x_test.shape)
model= Sequential([Embedding(vocab_size,128,input_length=max_len),SimpleRNN(64),Dense(1,activation='sigmoid')])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print("\nModel Architecture Summary")
model.summary()
history = model.fit(x_train,y_train,epochs=5,batch_size=64,validation_split=0.2)
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title("Training vs Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()
test_loss, test_acc = model.evaluate(x_test, y_test)
print("\nModel Evaluation")
print("Test Loss:", test_loss)
print("Test Accuracy:", test_acc)
predictions = model.predict(x_test)
y_pred = (predictions > 0.5).astype(int)
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
xticklabels=["Negative","Positive"],
yticklabels=["Negative","Positive"])
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()
print("\nclassification Report")
print(classification_report(y_test,y_pred))
print("\nSample Prediction Interpretation\n")
for i in range(5):
  probability=predictions[i][0]
  predicted_sentiment = "Positive" if probability > 0.5 else "Negative"
  actual_sentiment = "Positive" if y_test[i] == 1 else "Negative"
  print(f"Review {i+1}")
  print("Actual Sentiment :", actual_sentiment)
  print("Predicted Sentiment:", predicted_sentiment)
  print("Prediction Confidence:", round(probability,3))
  print("-"*40)